SportsStore/Controllers/AdminController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Domain.Interfaces;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    [Authorize]
    public class AdminController : Controller
    {
        private IEntityRepository<Product> _productService;

        public AdminController(IEntityRepository<Product> productService)
        {
            _productService = productService;
        }
        // GET: Admin
        public ActionResult Index()
        {
            return View(_productService.GetAll());
        }

        [HttpGet]
        public ActionResult Edit(int productID)
        {
            var product = _productService.GetById(productID);

            if (product == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(product);

        }

        [HttpPost]
        public ActionResult Edit(Product product, HttpPostedFileBase image = null)
        {
            if (ModelState.IsValid)
            {
                if(image != null)
                {
                    product.ImageMineType = image.ContentType;
                    product.ImageData = new byte[image.ContentLength];
                    image.InputStream.Read(product.ImageData, 0, image.ContentLength);
                }
                _productService.Update(product);
                _productService.Commit();
                TempData["message"] = string.Format("{0} has been saved", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Create(Product product)
        {
            if (ModelState.IsValid)
            {
                _productService.Add(product);
                _productService.Commit();
                TempData["message"] = string.Format("{0} has been added", product.Name);
                return RedirectToAction("Index");
            }
            else
            {
                return View(product);
            }
        }

        [HttpGet]
        public ActionResult Delete(int productID)
        {
            var product = _productService.GetById(productID);

            if (product == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            return View(product);
        }

        [HttpPost]
        [ActionName("Delete")]
        public ActionResult Deleted(int productID)
        {
            var product = _productService.GetById(productID);

            if (product == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.NotFound);
            }

            _productService.Delete(product);
            _productService.Commit();
            TempData["message"] = string.Format("{0} has been deleted", product.Name);
            return RedirectToAction("Index");
        }

    }
}

SportsStore/Controllers/ProductsController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class ProductsController : Controller
    {
        private IEntityRepository<Product> _productService;

        public ProductsController(IEntityRepository<Product> productService)
        {
            _productService = productService;
        }
        // GET: Products
        public ActionResult List()
        {
            return View();
        }

        public FileContentResult GetImage(int? productId)
        {
            if (productId.HasValue)
            {
            var product = _productService.GetById(productId.Value);
            if(product != null)
            {
                return File(product.ImageData, product.ImageMineType);
            }
                return null;

            }
            else
            {
                return null;
            }
        
        }
    }
}

SportsStore/Views/Shared/_AdminNavigation.cshtml
    <!-- Navigation -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("Index","Admin")">
                <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

SportsStore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Sports Store, Sports, Sporting Goods">
    <meta name="author" content="Trevor Smith">
    <title>Sports Store</title>
    <!-- Bootstrap Core CSS -->

    <link href="~/Content/css/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/css/shop-homepage.css" rel="stylesheet" />
    <!-- Custom CSS -->
    <link href="~/Content/toastr.css" rel="stylesheet" />
    <link href="~/Content/css/Main.css" rel="stylesheet" />
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>
    <!-- Page Content -->
    <div class="container">
        <div class="row">        
              @RenderBody()
        </div>
    </div>
    <!-- /.container -->
    <div class="container">
        <hr>
        <!-- Footer -->
        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p>Copyright &copy; Sports Store @DateTime.Now.Year</p>
                </div>
            </div>
        </footer>
    </div>
    <!-- /.container -->
    <!-- jQuery -->
    <script src="~/Scripts/jquery.js"></script>
    <script src="~/Scripts/jquery.validate.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.js"></script>>
    <!-- Bootstrap Core JavaScript -->
    <script src="~/Scripts/bootstrap.js"></script>
    <script src="~/Scripts/toastr.js"></script>
    <script src="~/Scripts/knockout-3.4.2.js"></script>
    @RenderSection("scripts",false)
</body>
</html>

SportsStore/Views/Shared/_Navigation.cshtml
    <!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("List","Products")">
                <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>