SportsStore/Controllers/CartsController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Models;
using SportsStore.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace SportsStore.Controllers
{
    public class CartsController : Controller
    {

        private readonly IEntityRepository<Product> _productsRepository;

        public CartsController(IEntityRepository<Product> productsRepository)
        {
            _productsRepository = productsRepository;
        }
        // GET: Carts
        //Lets let this just serve a view
        public ViewResult Index()
        {
            return View();
        }

        public ActionResult AddToCart(int productId)
        {
            var product = _productsRepository.GetById(productId);

            if(product == null)
            {
                return new HttpNotFoundResult();
            }

            GetCart().AddItem(product, 1);
            return Json(new { Cart = GetCart(), Product = product },JsonRequestBehavior.AllowGet);
        }


        public ActionResult RemoveFromCart(int productId)
        {
            var product = _productsRepository.GetById(productId);

            if (product == null)
            {
                return new HttpNotFoundResult();
            }

            GetCart().RemoveLine(product);
            return Json(new { Cart = GetCart(), Product = product }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ClearAllCartItems()
        {
            GetCart().Clear();
            return Json(new { Message = "Cart has been cleared" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAllItems()
        {
            return Json(new { Cart = GetCart(), Return = "Ok" }, JsonRequestBehavior.AllowGet);
        }

        private CartService GetCart()
        {
            var cart = (CartService)Session["CartService"];

            if(cart == null)
            {
                cart = new CartService();
                Session["CartService"] = cart;
            }

            return cart;
        }
    }
}

SportsStore/Controllers/OrderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class OrderController : Controller
    {
        // GET: Order
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Success()
        {
            return View();
        }

        public ActionResult Cancelled()
        {
            return View();
        }
    }
}

SportsStore/Controllers/ProductsController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class ProductsController : Controller
    {
        private IEntityRepository<Product> _productService;

        public ProductsController(IEntityRepository<Product> productService)
        {
            _productService = productService;
        }
        // GET: Products
        public ActionResult List()
        {
            return View();
        }

        public FileContentResult GetImage(int? productId)
        {
            if (productId.HasValue)
            {
            var product = _productService.GetById(productId.Value);
            if(product != null)
            {
                return File(product.ImageData, product.ImageMineType);
            }
                return null;

            }
            else
            {
                return null;
            }
        
        }
    }
}

SportsStore/Views/Carts/Index.cshtml
@{
    ViewBag.Title = "Cart";
}

@section scripts{
    <script src="~/Scripts/app/common/Constants.js"></script>
    <script src="~/Scripts/app/data/SportsStoreDataService.js"></script>
    <script src="~/Scripts/app/common/Logger.js"></script>
    <script src="~/Scripts/app/ui/viewmodels/CartViewModel.js"></script>
    <script src="~/Scripts/app/ui/controllers/CartController.js"></script>

    <script>
        (function () {
             var cartController = new SportsStore.CartController();
             cartController.PageLoad();
         })();
    </script>

}
@Html.Partial("_Navigation")
<div class="jumbotron" data-bind="visible: cartList().length === 0">
    <p>You have no items in the cart..</p>
    <a href="@Url.Action("List","Products")" class="btn btn-primary">
        <span class="glyphicon glyphicon-shopping-cart"></span>
        Continue Shopping
    </a>

</div>
<div data-bind="visible: cartList().length > 0">
    <h2 class="text-muted text-center">Your Cart</h2>


        <table class="table">
            <thead>
                <tr>
                    <th>Product Image</th>
                    <th>Quantity</th>
                    <th>Item</th>
                    <th>Price</th>
                    <th class="text-right">Subtotal</th>
                </tr>
            </thead>
            <tbody data-bind="foreach: cartList">
                <tr>

                    <td><img style="width:60px; height:60px; border:inset" data-bind="attr:{src: '@Url.Action("GetImage","Products")' + '?productId=' + $data.Product.ProductID }" alt=""></td>
                    <td data-bind="text: $data.Quantity"></td>
                    <td data-bind="text: $data.Product.Name"></td>
                    <td data-bind="text: '$' + $data.Product.Price.toFixed(2)"></td>
                    <td class="text-right" data-bind="text: '$' + ($data.Quantity * $data.Product.Price).toFixed(2)"></td>
                    <td>
                        <button class="btn btn-danger btn-sm pull-right" data-bind="click: $parent.removeItem">
                            <span class="glyphicon glyphicon-trash"></span>
                            Remove
                        </button>
                    </td>
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <td colspan="2"></td>
                    <td>Total:</td>
                    <td class="text-right" data-bind="text: '$' + cartTotal().toFixed(2)"></td>
                </tr>
            </tfoot>
        </table>

    <div class="text-center">
        <a href="@Url.Action("List","Products")" style="width:200px" class="btn btn-primary">
            <span class="glyphicon glyphicon-shopping-cart"></span>
            Continue Shopping
        </a>
        <a href="@Url.Action("Index","Order")" style="width:200px" class="btn btn-default">
            <span class="glyphicon glyphicon-usd"></span>
            Place Order
        </a>
    </div>
</div>