SportsStore/ViewModels/ProductsViewModel.cs
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace SportsStore.ViewModels
{
    public class ProductsViewModel
    {
        public IEnumerable<Product> Products { get; set; }
        public IEnumerable<string> Categories { get; set; }
    }
}

SportsStore/Controllers/CartsController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Models;
using SportsStore.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;


namespace SportsStore.Controllers
{
    public class CartsController : Controller
    {

        private readonly IEntityRepository<Product> _productsRepository;

        public CartsController(IEntityRepository<Product> productsRepository)
        {
            _productsRepository = productsRepository;
        }
        // GET: Carts
        //Lets let this just serve a view
        public ViewResult Index()
        {
            return View();
        }

        public ActionResult AddToCart(int productId)
        {
            var product = _productsRepository.GetById(productId);

            if(product == null)
            {
                return new HttpNotFoundResult();
            }

            GetCart().AddItem(product, 1);
            return Json(new { Cart = GetCart(), Product = product },JsonRequestBehavior.AllowGet);
        }


        public ActionResult RemoveFromCart(int productId)
        {
            var product = _productsRepository.GetById(productId);

            if (product == null)
            {
                return new HttpNotFoundResult();
            }

            GetCart().RemoveLine(product);
            return Json(new { Cart = GetCart(), Product = product }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ClearAllCartItems()
        {
            GetCart().Clear();
            return Json(new { Message = "Cart has been cleared" }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetAllItems()
        {
            return Json(new { Cart = GetCart(), Return = "Ok" }, JsonRequestBehavior.AllowGet);
        }

        private CartService GetCart()
        {
            var cart = (CartService)Session["CartService"];

            if(cart == null)
            {
                cart = new CartService();
                Session["CartService"] = cart;
            }

            return cart;
        }
    }
}

SportsStore/Controllers/ProductsController.cs
using SportsStore.Domain.Abstract;
using SportsStore.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SportsStore.Controllers
{
    public class ProductsController : Controller
    {
        private IEntityRepository<Product> _productService;

        public ProductsController(IEntityRepository<Product> productService)
        {
            _productService = productService;
        }
        // GET: Products
        public ActionResult List()
        {
            return View();
        }

        public FileContentResult GetImage(int? productId)
        {
            if (productId.HasValue)
            {
            var product = _productService.GetById(productId.Value);
            if(product != null)
            {
                return File(product.ImageData, product.ImageMineType);
            }
                return null;

            }
            else
            {
                return null;
            }
        
        }
    }
}

SportsStore/Views/Products/List.cshtml
@section scripts{
<script src="~/Scripts/app/common/Constants.js"></script>
<script src="~/Scripts/app/data/SportsStoreDataService.js"></script>
<script src="~/Scripts/app/common/Logger.js"></script>
<script src="~/Scripts/app/ui/viewmodels/ProductsViewModel.js"></script>
<script src="~/Scripts/app/ui/controllers/ProductsController.js"></script>

<script>
         (function () {
             var productsController = new SportsStore.ProductsController();
             productsController.PageLoad();
         })();
</script>

}
<div class="modal fade col-md-offset-6 col-md-1" id="busyindicator" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-dialog vertical-align-center">
            <div class="progress">
                <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="100" aria-valuemin="0" aria-valuemax="100" style="width: 100%">
                </div>
            </div>
        </div>
    </div>
</div>
    <!-- Navigation -->
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="@Url.Action("List","Products")">
                <span class="glyphicon glyphicon-new-window" aria-hidden="true"></span>
            </a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li>
                    <a href="#">About</a>
                </li>
                <li>
                    <a href="#">Services</a>
                </li>
                <li>
                    <a href="#">Contact</a>
                </li>
            </ul>
            <div class="navbar-right" id="cart-details">
                <a id="cart" href="@Url.Action("Index","Carts")" data-bind="click: showCart">
                    <span style="margin-top:20px;" class="glyphicon glyphicon-shopping-cart"></span>
                    <span class="badge" data-bind="text: cartList().length"></span>
                </a>
                <div id="cart-summary" style="display:none">
                    <span data-bind="visible: cartList().length == 0">
                        Cart empty
                    </span>
                    <div data-bind="visible: cartList().length > 0">
                        <ol>
                            <!-- ko foreach:{data: cartList, afterAdd: fadeIn }-->
                            <li data-bind="text: $data.Product.Name"></li>
                            <!-- /ko -->
                        </ol>
                        <p><strong>Total: </strong>$<span data-bind="text: cartTotal"></span></p>
                        <br />
                        <a href="@Url.Action("Index","Carts")" class="btn btn-primary btn-sm">
                        <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                        View Cart Details</a>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>

<div class="col-md-3">
    <p class="lead">Sports Store</p>
    <div class="list-group">
        <a data-bind="click: setCategory.bind('Home')" href="#" class="list-group-item text-center">Home</a>
        <!-- ko foreach: categoriesList -->
        <a href="#" class="list-group-item text-center" data-bind="click: $parent.setCategory.bind($data), text: $data"></a>
        <!-- /ko -->
    </div>
</div>
<div class="col-md-9">
    <div class="row carousel-holder">
        <div class="col-md-12">
            <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
                <ol class="carousel-indicators">
                    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
                    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
                </ol>
                <div class="carousel-inner">
                    <div class="item active">
                        <img class="slide-image" src="http://placehold.it/800x300" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="http://placehold.it/800x300" alt="">
                    </div>
                    <div class="item">
                        <img class="slide-image" src="http://placehold.it/800x300" alt="">
                    </div>
                </div>
                <a class="left carousel-control" href="#carousel-example-generic" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left"></span>
                </a>
                <a class="right carousel-control" href="#carousel-example-generic" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right"></span>
                </a>
            </div>
        </div>
    </div>
    <div data-bind="foreach: productsList" class="row">
        <div class="col-sm-4 col-lg-4 col-md-4">
            <div class="thumbnail">
                <img style="width:100px; height:100px;" data-bind="attr:{src: '@Url.Action("GetImage","Products")' + '?productId=' + $data.ProductID }" alt="">
                <div class="caption">
                    <h4 data-bind="text: '$' +  $data.Price.toFixed(2)" class="pull-right"></h4>
                    <h4>
                        <span data-bind="text: $data.Name"></span>
                    </h4>
                    <button data-bind="click: $parent.addToCart" class="btn btn-primary pull-right">
                        <span class="glyphicon glyphicon-plus">
                        </span>
                        Add to cart
                    </button>
                </div>
           
            </div>
        </div>
    </div>
    </div>